//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManage.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookManage.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string iabout {
            get {
                return ResourceManager.GetString("iabout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN.
        /// </summary>
        public static string iad {
            get {
                return ResourceManager.GetString("iad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOPPING CART.
        /// </summary>
        public static string icart {
            get {
                return ResourceManager.GetString("icart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        public static string IDatHang {
            get {
                return ResourceManager.GetString("IDatHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COSTOMER SERVICE.
        /// </summary>
        public static string iDVKH {
            get {
                return ResourceManager.GetString("iDVKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Home.
        /// </summary>
        public static string iGTHome {
            get {
                return ResourceManager.GetString("iGTHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string ihome {
            get {
                return ResourceManager.GetString("ihome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        public static string iinfo {
            get {
                return ResourceManager.GetString("iinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string ilogin {
            get {
                return ResourceManager.GetString("ilogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN OUT.
        /// </summary>
        public static string iout {
            get {
                return ResourceManager.GetString("iout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string ispecial {
            get {
                return ResourceManager.GetString("ispecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string ith1 {
            get {
                return ResourceManager.GetString("ith1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiction.
        /// </summary>
        public static string ith2 {
            get {
                return ResourceManager.GetString("ith2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health &amp; Fitness.
        /// </summary>
        public static string ith3 {
            get {
                return ResourceManager.GetString("ith3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string ith4 {
            get {
                return ResourceManager.GetString("ith4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery.
        /// </summary>
        public static string ith5 {
            get {
                return ResourceManager.GetString("ith5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politics &amp; Current Affairs.
        /// </summary>
        public static string ith6 {
            get {
                return ResourceManager.GetString("ith6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relligion.
        /// </summary>
        public static string ith7 {
            get {
                return ResourceManager.GetString("ith7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALE.
        /// </summary>
        public static string ith8 {
            get {
                return ResourceManager.GetString("ith8", resourceCulture);
            }
        }
    }
}
